apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  password: cGFzc3dvcmQ=